import type { Agendamento } from "./types";

/**
 * "Hoje" fixo para esta etapa mockada: os dados abaixo giram em torno de 21/08/2026 para
 * a Agenda vir sempre povoada ao abrir a tela, independente da data real do sistema.
 * Quando a API real existir, isso deixa de existir e passa a usar `new Date()`.
 */
export const MOCK_TODAY = new Date(2026, 7, 21); // 21 de agosto de 2026 (mês 0-indexado)

const EMPRESA = "EMP001";

/** >= 12 agendamentos reais exigidos, distribuídos de segunda a sábado da semana. */
export const MOCK_AGENDAMENTOS: Agendamento[] = [
  {
    idAgendamento: "AGD001",
    idEmpresa: EMPRESA,
    idCliente: "CLI001",
    idProfissional: "PROF001",
    idServico: "SRV001",
    clienteNome: "Beatriz Nogueira",
    clienteTelefone: "(34) 99811-2233",
    profissionalNome: "Ana Martins",
    servicoNome: "Manicure simples",
    data: "2026-08-17",
    horaInicio: "09:00",
    horaFim: "10:00",
    status: "CONFIRMADO",
    valor: 45,
  },
  {
    idAgendamento: "AGD002",
    idEmpresa: EMPRESA,
    idCliente: "CLI002",
    idProfissional: "PROF002",
    idServico: "SRV002",
    clienteNome: "Larissa Ferreira",
    clienteTelefone: "(34) 99822-3344",
    profissionalNome: "Carla Souza",
    servicoNome: "Design de sobrancelhas",
    data: "2026-08-17",
    horaInicio: "14:00",
    horaFim: "15:30",
    status: "CONCLUIDO",
    valor: 60,
  },
  {
    idAgendamento: "AGD003",
    idEmpresa: EMPRESA,
    idCliente: "CLI003",
    idProfissional: "PROF001",
    idServico: "SRV003",
    clienteNome: "Fernanda Lima",
    clienteTelefone: "(34) 99833-4455",
    profissionalNome: "Ana Martins",
    servicoNome: "Pedicure",
    data: "2026-08-18",
    horaInicio: "10:00",
    horaFim: "11:00",
    status: "CONFIRMADO",
    valor: 50,
  },
  {
    idAgendamento: "AGD004",
    idEmpresa: EMPRESA,
    idCliente: "CLI004",
    idProfissional: "PROF002",
    idServico: "SRV004",
    clienteNome: "Juliana Rocha",
    clienteTelefone: "(34) 99844-5566",
    profissionalNome: "Carla Souza",
    servicoNome: "Escova modelada",
    data: "2026-08-18",
    horaInicio: "16:00",
    horaFim: "17:00",
    status: "PENDENTE",
    valor: 70,
  },
  {
    idAgendamento: "AGD005",
    idEmpresa: EMPRESA,
    idCliente: "CLI005",
    idProfissional: "PROF001",
    idServico: "SRV005",
    clienteNome: "Camila Duarte",
    clienteTelefone: "(34) 99855-6677",
    profissionalNome: "Ana Martins",
    servicoNome: "Manicure em gel",
    data: "2026-08-19",
    horaInicio: "09:30",
    horaFim: "10:30",
    status: "CONFIRMADO",
    valor: 80,
  },
  {
    idAgendamento: "AGD006",
    idEmpresa: EMPRESA,
    idCliente: "CLI006",
    idProfissional: "PROF002",
    idServico: "SRV006",
    clienteNome: "Rafaela Costa",
    clienteTelefone: "(34) 99866-7788",
    profissionalNome: "Carla Souza",
    servicoNome: "Sobrancelha com henna",
    data: "2026-08-19",
    horaInicio: "13:00",
    horaFim: "14:00",
    status: "CANCELADO",
    valor: 55,
  },
  {
    idAgendamento: "AGD007",
    idEmpresa: EMPRESA,
    idCliente: "CLI007",
    idProfissional: "PROF001",
    idServico: "SRV007",
    clienteNome: "Vanessa Alves",
    clienteTelefone: "(34) 99877-8899",
    profissionalNome: "Ana Martins",
    servicoNome: "Pedicure spa",
    data: "2026-08-20",
    horaInicio: "08:30",
    horaFim: "09:30",
    status: "CONFIRMADO",
    valor: 90,
  },
  {
    idAgendamento: "AGD008",
    idEmpresa: EMPRESA,
    idCliente: "CLI008",
    idProfissional: "PROF002",
    idServico: "SRV008",
    clienteNome: "Priscila Martins",
    clienteTelefone: "(34) 99888-9900",
    profissionalNome: "Carla Souza",
    servicoNome: "Alongamento em fibra",
    data: "2026-08-20",
    horaInicio: "15:00",
    horaFim: "16:30",
    status: "PENDENTE",
    valor: 150,
  },
  {
    idAgendamento: "AGD009",
    idEmpresa: EMPRESA,
    idCliente: "CLI009",
    idProfissional: "PROF001",
    idServico: "SRV009",
    clienteNome: "Mariana Silva",
    clienteTelefone: "(34) 99999-1122",
    profissionalNome: "Ana Martins",
    servicoNome: "Alongamento em gel",
    data: "2026-08-21",
    horaInicio: "09:00",
    horaFim: "11:00",
    status: "CONFIRMADO",
    valor: 120,
  },
  {
    idAgendamento: "AGD010",
    idEmpresa: EMPRESA,
    idCliente: "CLI010",
    idProfissional: "PROF001",
    idServico: "SRV010",
    clienteNome: "Camila Souza",
    clienteTelefone: "(34) 99999-2233",
    profissionalNome: "Ana Martins",
    servicoNome: "Manutenção de gel",
    data: "2026-08-21",
    horaInicio: "11:30",
    horaFim: "13:00",
    status: "CONFIRMADO",
    valor: 90,
  },
  {
    idAgendamento: "AGD011",
    idEmpresa: EMPRESA,
    idCliente: "CLI011",
    idProfissional: "PROF001",
    idServico: "SRV011",
    clienteNome: "Jéssica Almeida",
    clienteTelefone: "(34) 99999-3344",
    profissionalNome: "Ana Martins",
    servicoNome: "Esmaltação em gel",
    data: "2026-08-21",
    horaInicio: "14:30",
    horaFim: "15:30",
    status: "PENDENTE",
    valor: 70,
  },
  {
    idAgendamento: "AGD012",
    idEmpresa: EMPRESA,
    idCliente: "CLI012",
    idProfissional: "PROF001",
    idServico: "SRV010",
    clienteNome: "Patrícia Mendes",
    clienteTelefone: "(34) 99999-4455",
    profissionalNome: "Ana Martins",
    servicoNome: "Manutenção de gel",
    data: "2026-08-21",
    horaInicio: "17:00",
    horaFim: "18:30",
    status: "CONCLUIDO",
    valor: 90,
  },
  {
    idAgendamento: "AGD013",
    idEmpresa: EMPRESA,
    idCliente: "CLI013",
    idProfissional: "PROF002",
    idServico: "SRV008",
    clienteNome: "Débora Nascimento",
    clienteTelefone: "(34) 98811-5566",
    profissionalNome: "Carla Souza",
    servicoNome: "Alongamento em fibra",
    data: "2026-08-22",
    horaInicio: "10:00",
    horaFim: "11:30",
    status: "CONFIRMADO",
    valor: 140,
  },
  {
    idAgendamento: "AGD014",
    idEmpresa: EMPRESA,
    idCliente: "CLI014",
    idProfissional: "PROF001",
    idServico: "SRV002",
    clienteNome: "Aline Barbosa",
    clienteTelefone: "(34) 98822-6677",
    profissionalNome: "Ana Martins",
    servicoNome: "Design de sobrancelhas",
    data: "2026-08-22",
    horaInicio: "13:00",
    horaFim: "14:00",
    status: "CONFIRMADO",
    valor: 60,
  },
];
